### ISSUE TITLE
说明文档文末超链接一丶小问题

### ISSUE THREAD

**Issue by MuChengZJU** [NiJingzhe/2DGameEngine_Based_On_LibGraphics#19]
文末超链接把尾括号识别进去了，导致gitee404（悲）
https://gitee.com/ni-jingzhe/2-dgame-engine-based-on-lib-graphics）
加个空格应该就好了

**Comment by MuChengZJU** [comment]
https://github.com/NiJingzhe/2DGameEngine_Based_On_LibGraphics/blob/master/2D游戏引擎GELG说明文档.md这里的问题

**Comment by NiJingzhe** [comment]
已经修好啦！感谢提醒
